# Análisis de Medallas Olímpicas

### Objetivo
Realizar un análisis exploratorio de datos (EDA) sobre un conjunto de datos de medallas olímpicas utilizando Pandas. Este proyecto te permitirá aplicar los conceptos aprendidos sobre **Series**, **DataFrames**, **limpieza de datos**, **operaciones básicas**, **filtrado** y **agregación** en Pandas.

### Consigna
Vas a trabajar con el conjunto de datos *medallas.csv*, que incluye información sobre las medallas de oro, plata, bronce y el total obtenido por cada país en los Juegos Olímpicos.

Vas a realizar una serie de tareas básicas, que te permitirán responder a las preguntas del **cuestionario** que encontrarás al final del día. Las tareas que realizarás son:

1. **Cargar los Datos**: Importar los datos desde el archivo CSV a un DataFrame de Pandas.

2. **Exploración Inicial**: Utilizar métodos básicos para explorar el tamaño, las columnas y los tipos de datos del DataFrame.

3. **Limpieza de Datos**: Identificar y manejar valores faltantes o incorrectos, especialmente en las columnas de medallas donde los valores faltantes indican cero medallas.

4. **Análisis de Medallas de Oro por País**: Realiza las operaciones que sean necesarias para identificar cuáles fueron los 3 países con más medallas de Oro en total (vas a necesitar investigar los métodos de dataframes para encontrar cuál te permite ordenar los valores de mayor a menor o viceversa).

5. **Análisis de Medallas Totales por País**: Obtener un dataframe que contenga sólo los países que ganaron más de 10 medallas en total.

In [1]:
import pandas as pd
df = pd.read_csv("medallas.csv")

In [2]:
df.head()

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [3]:
df.tail()

    Oro  Plata  Bronce  Total          Pais
88  NaN    1.0     NaN      1  Turkmenistan
89  2.0    1.0     1.0      4        Uganda
90  1.0    6.0    12.0     19       Ukraine
91  3.0    NaN     2.0      5    Uzbekistan
92  1.0    3.0     NaN      4     Venezuela

In [4]:
df[["Oro","Plata","Bronce"]] = df[["Oro","Plata","Bronce"]].fillna(0)
df[["Oro","Plata","Bronce"]] = df[["Oro","Plata","Bronce"]].astype(int)

In [5]:
df.head()

   Oro  Plata  Bronce  Total        Pais
0    0      1       2      3   Argentina
1    0      2       2      4     Armenia
2   17      7      22     46   Australia
3    1      1       5      7     Austria
4    0      3       4      7  Azerbaijan

In [7]:
df_a = df.sort_values(by="Oro",ascending=False).head(3)
df_a

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
46   27     14      17     58                       Japon

In [8]:
filtro = df["Total"] > 10
df_t = df[filtro]
df_t

    Oro  Plata  Bronce  Total                        Pais
2    17      7      22     46                   Australia
11    7      6       8     21                      Brazil
14    7      6      11     24                      Canada
15    2      4       6     12              Chinese Taipei
19    7      3       5     15                        Cuba
20    4      4       3     11              Czech Republic
21    3      4       4     11                     Denmark
25   39     41      33    113   Estados Unidos de America
30    1     12      11     33                      France
32    1     11      16     37                     Germany
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
60    1     12      14     36                 Netherlands
66    4      5       5     14                      Poland
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
81    3      8       6     17                       Spain
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
90    1      6      12     19                     Ukraine